spring:
  application:
    name: post-service
  data:
    mongodb:
      database: ${MONGODB_SCHEMA:testing-final}
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}

server:
  port: 8090
#  error:
#    include-binding-errors: always
#    include-message: always

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:${random.uuid}
