spring:
  application:
    name: post-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bni-bootcamp
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8090

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:${random.uuid}